"use client";
import { useEffect, useState } from "react";
import { Heart, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import GlitterBackground from "../../../components/GlitterBackground";
import RakhiButton from "../../../components/RakhiButton";
import RakhiJourney from "../../../components/RakhiJourney";
import { getActiveRecord } from "../../../lib/rakhi";
export default function JourneyPage(){const router=useRouter();const [progress,setProgress]=useState(0);const [details,setDetails]=useState({sisterCity:"Her city",brotherCity:"Your city",brotherName:"Brother"});useEffect(()=>{const record=getActiveRecord();const brother=record?.brother;if(!record||!brother){router.replace("/create");return;}const setup=window.setTimeout(()=>setDetails({sisterCity:record.sister.location,brotherCity:brother.location,brotherName:brother.name}),0);const timer=window.setInterval(()=>setProgress(value=>Math.min(100,value+1)),55);return()=>{window.clearTimeout(setup);window.clearInterval(timer);};},[router]);const arrived=progress===100;return <main className="relative min-h-screen overflow-hidden bg-[#FFFDF8] text-[#40364A]"><GlitterBackground/><section className="relative z-10 mx-auto flex min-h-screen max-w-md flex-col px-5 py-9 text-center"><p className="flex items-center justify-center gap-2 text-[10px] uppercase tracking-[.25em] text-[#8068A8]"><Sparkles size={12}/>A Rakhi is travelling<Sparkles size={12}/></p><h1 className="mt-5 font-serif text-4xl">Love knows <span className="block italic text-[#8068A8]">no distance.</span></h1><p className="mt-4 text-sm leading-6 text-[#756C78]">Crossing the distance, carrying a little love with it.</p><RakhiJourney progress={progress} sisterCity={details.sisterCity} brotherCity={details.brotherCity}/>{!arrived?<div className="mt-6"><p className="font-serif text-xl">Your Rakhi is travelling...</p><p className="mt-2 text-xs text-[#918895]">{progress}% of the journey complete</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#E9E1E5]"><div className="h-full rounded-full bg-[#8068A8]" style={{width:`${progress}%`}}/></div></div>:<div className="mt-7"><Heart className="mx-auto text-[#8068A8]" fill="currentColor"/><p className="mt-3 font-serif text-2xl">It made it to you, {details.brotherName}. ❤️</p><p className="mt-2 text-sm text-[#756C78]">A little piece of home has crossed the distance.</p></div>}{arrived&&<RakhiButton onClick={()=>router.push("/rakhi/message")} className="mt-auto">OPEN YOUR RAKHI</RakhiButton>}</section></main>}
